jenkins:
  extends:
    file: docker-compose-template.yml
    service: jenkins
  volumes:
    - ./jenkins/jenkins_home:/var/jenkins_home
    - /Users/david/.docker/machine/machines:/var/.docker/machine/machines
